-
    version: '7.4.0.{build}'
    os: Visual Studio 2022

    configuration: Release
    platform:
        - x64
    branches:
      only:
        - master
        
    environment:
        TokenSecureGit: BbvaBqBiF0qP5ne21acir4wbozoKTL7ssMDQhD/I20qAUrP/uTGrgcJwx5FnHHFNMnepN3lQcZpnkD+RARpBeweMw/Z3SR8TfFWtMsM0Gh4=
        MyProjectDir: C:\projects\genshinimpact-autotrack-dll\
        OpenCvDir: C:\projects\opencv\
        OpenCvUrl: https://github.com/GengGode/OpencvStaticLib/releases/download/4.6.0/Opencv.zip
        ProjectName: cvAutoTrack
        ProJectExeName: cvAutoTrack
    skip_tags: true
  
    install:
        - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()
        - echo %APPVEYOR_BUILD_VERSION%>>%MyProjectDir%cvAutoTrack\src\version\appVeyor_version_tag.tag
        - mkdir %OpenCvDir%
        - appveyor DownloadFile %OpenCvUrl%
        - 7z x ./*.zip -y -o%OpenCvDir%
        - rm -f ./*.zip
        #- dir %OpenCvDir%
        #- dir %OpenCvDir%x64\vc15\staticlib

        - cd %MyProjectDir%\%ProjectName%\
        - 7z x ./resource.rar -y -o%MyProjectDir%\%ProjectName%\
    before_build:
        #- dir  %MyProjectDir%
        #- dir  %OpenCvDir%

    build_script:
        - MSBuild %MyProjectDir%cvAutoTrack\cvAutoTrack.vcxproj /p:configuration="Compile"
        # 编译测试文件
        - MSBuild %MyProjectDir%impl\Cpp\TEST_cvAutoTrack_Cpp\TEST_cvAutoTrack_Cpp.vcxproj /p:configuration="Compile"
        - MSBuild %MyProjectDir%impl\CSharp\TEST_cvAutoTrack_CSharp\TEST_cvAutoTrack_CSharp.csproj /t:restore
        - MSBuild %MyProjectDir%impl\CSharp\TEST_cvAutoTrack_CSharp\TEST_cvAutoTrack_CSharp.csproj /p:configuration="Compile"

    after_build:
        - echo %MyProjectDir%cvAutoTrack.sln 编译完成 等待测试
        - mkdir %MyProjectDir%x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.dll $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.lib $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\include\*.h $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\cvAutoTrackCSharp.cs $env:MyProjectDir\x64\build\
        
        # 从文件中读取 $version_tag.tag 设置 AppVeyor 版本
        - ps: $env:APPVEYOR_BUILD_VERSION=$(Get-Content -Path $env:MyProjectDir\cvAutoTrack\src\version\version_tag.tag)  
        - ps: echo $env:APPVEYOR_BUILD_VERSION
        
    before_test:
        # 移动测试文件到test目录
        - mkdir %MyProjectDir%x64\test\
        - cd %MyProjectDir% 
        - ls -R
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.dll $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\Cpp\TEST_cvAutoTrack_Cpp\x64\Compile\*.exe $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.exe $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.dll $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.json $env:MyProjectDir\x64\test\
        
    test_script:
        - cd %MyProjectDir%\x64\test\
        - dir
        # 运行 C++ 测试
        - TEST_cvAutoTrack_Cpp.exe -test
        # 运行 C# 测试
        - TEST_cvAutoTrack_CSharp.exe -test
        
    after_test:
        - cd %MyProjectDir%x64\build\
        - echo %APPVEYOR_BUILD_VERSION% >version.tag
        - md5sum -b %MyProjectDir%x64\build\%ProjectName%.dll | cut -c 2-34 >%ProjectName%.md5
        - 7z a cvautotrack.7z %MyProjectDir%x64\build\*
        - ps: cp -r $env:MyProjectDir\impl\Cpp\TEST_cvAutoTrack_Cpp\x64\Compile\TEST_cvAutoTrack_Cpp.exe $env:MyProjectDir\x64\build\

        - 
        
        - appveyor PushArtifact version.tag
        - appveyor PushArtifact %ProjectName%.md5
        - appveyor PushArtifact cvAutoTrack.7z
        - appveyor PushArtifact TEST_cvAutoTrack_Cpp.exe


    #artifacts:
        #- path: build/Release
        #artifacts path name must be appveyor API
  
    deploy:
        - provider: GitHub
          description: '$(APPVEYOR_PROJECT_SLUG): cvAutoTrack Dll $(APPVEYOR_BUILD_VERSION).$(APPVEYOR_BUILD_NUMBER)' 
          auth_token:
             secure: G/Fzf0bGIhqqt+XvsC5AXrZVNs3atGU7XCzJxqiUZEwOxoZrjxk87ENI/OitnXCo
          draft: false
          tag: $(APPVEYOR_BUILD_VERSION)
          force_update: true
          on:  
            APPVEYOR_REPO_TAG: false

    notifications:
      - provider: Email
        to:
          - ysx20201030@163.com
          - aymb00@126.com
        subject: '{{status}}: {{projectName}} {{buildVersion}}'                  # optional
        message: "<h1>Build</h1>
                    <h2>{{projectName}} {{status}}</h2>
                        <p>{{buildVersion}}: {{buildUrl}}</p>
                   <H1>Commit</h1> 
                    <h3>#{{commitId}} by {{commitAuthor}} on {{commitDate}}</h3><h2> {{commitMessage}}</h2>"    # optional
        on_build_success: true
        on_build_failure: false
        on_build_status_changed: false
-
    version: '7.0.0.{build}'
    os: Visual Studio 2022
    configuration: Dev
    platform:
        - x64
    branches:
      only:
        - /dev-/

    environment:
        MyProjectDir: C:\projects\genshinimpact-autotrack-dll\
        OpenCvDir: C:\projects\opencv\
        OpenCvUrl: https://github.com/GengGode/OpencvStaticLib/releases/download/4.6.0/Opencv.zip
        ProjectName: cvAutoTrack
        ProJectExeName: cvAutoTrack
    skip_tags: true
  
    install:
        - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()
        # 发布版本号为 APPVEYOR_BUILD_VERSION 去除 {build}
        - ps: $env:APPVEYOR_BUILD_VERSION=$env:APPVEYOR_BUILD_VERSION.split('.')[0..2] -join '.'
        # 显示运行名称和版本号
        - ps: echo %APPVEYOR_BUILD_VERSION% 
        - ps: echo %APPVEYOR_BUILD_WORKER_IMAGE%

        - mkdir %OpenCvDir%
        - appveyor DownloadFile %OpenCvUrl%
        - 7z x ./*.zip -y -o%OpenCvDir%
        - rm -f ./*.zip

        - cd %MyProjectDir%\%ProjectName%\
        - 7z x ./resource.rar -y -o%MyProjectDir%\%ProjectName%\
        
    build_script:
        - MSBuild %MyProjectDir%cvAutoTrack\cvAutoTrack.vcxproj /p:configuration="Compile"
        # 编译测试文件
        - MSBuild %MyProjectDir%impl\Cpp\TEST_cvAutoTrack_Cpp\TEST_cvAutoTrack_Cpp.vcxproj /p:configuration="Compile"
        - MSBuild %MyProjectDir%impl\CSharp\TEST_cvAutoTrack_CSharp\TEST_cvAutoTrack_CSharp.csproj /t:restore
        - MSBuild %MyProjectDir%impl\CSharp\TEST_cvAutoTrack_CSharp\TEST_cvAutoTrack_CSharp.csproj /p:configuration="Compile"
        
    after_build:
        - echo %MyProjectDir%cvAutoTrack.sln 编译完成 等待测试
        - mkdir %MyProjectDir%x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.dll $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.lib $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\include\*.h $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\cvAutoTrackCSharp.cs $env:MyProjectDir\x64\build\
        
        # 从文件中读取 $version_tag.tag 设置 AppVeyor 版本
        #- $env:APPVEYOR_BUILD_VERSION = Get-Content -Path $env:MyProjectDir\cvAutoTrack\src\version\version_tag.tag   
        
        
    before_test:
        # 移动测试文件到test目录
        - mkdir %MyProjectDir%x64\test\
        - cd %MyProjectDir% 
        - ls -R
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.dll $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\Cpp\TEST_cvAutoTrack_Cpp\x64\Compile\*.exe $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.exe $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.dll $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.json $env:MyProjectDir\x64\test\
        
    test_script:
        - cd %MyProjectDir%\x64\test\
        - dir
        # 运行 C++ 测试
        - TEST_cvAutoTrack_Cpp.exe -test
        # 运行 C# 测试
        - TEST_cvAutoTrack_CSharp.exe -test
        
    after_test:
        - cd %MyProjectDir%x64\build\
        - echo %APPVEYOR_BUILD_VERSION% >version.tag
        - md5sum -b %MyProjectDir%x64\build\%ProjectName%.dll | cut -c 2-34 >%ProjectName%.md5
        - 7z a cvautotrack.7z %MyProjectDir%x64\build\*
        - ps: cp -r $env:MyProjectDir\impl\Cpp\TEST_cvAutoTrack_Cpp\x64\Compile\TEST_cvAutoTrack_Cpp.exe $env:MyProjectDir\x64\build\
        
        - appveyor PushArtifact version.tag
        - appveyor PushArtifact %ProjectName%.md5
        - appveyor PushArtifact cvAutoTrack.7z
        - appveyor PushArtifact TEST_cvAutoTrack_Cpp.exe

-
    version: '7.0.0.{build}'
    os: Visual Studio 2022
    configuration: Fix
    platform:
        - x64
    branches:
      only:
        - /fix-/

    environment:
        MyProjectDir: C:\projects\genshinimpact-autotrack-dll\
        OpenCvDir: C:\projects\opencv\
        OpenCvUrl: https://github.com/GengGode/OpencvStaticLib/releases/download/4.6.0/Opencv.zip
        ProjectName: cvAutoTrack
        ProJectExeName: cvAutoTrack
    skip_tags: true
  
    install:
        - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()

        - mkdir %OpenCvDir%
        - appveyor DownloadFile %OpenCvUrl%
        - 7z x ./*.zip -y -o%OpenCvDir%
        - rm -f ./*.zip

        - cd %MyProjectDir%\%ProjectName%\
        - 7z x ./resource.rar -y -o%MyProjectDir%\%ProjectName%\
        
    build_script:
        - MSBuild %MyProjectDir%cvAutoTrack\cvAutoTrack.vcxproj /p:configuration="Compile"
        # 编译测试文件
        - MSBuild %MyProjectDir%impl\Cpp\TEST_cvAutoTrack_Cpp\TEST_cvAutoTrack_Cpp.vcxproj /p:configuration="Compile"
        - MSBuild %MyProjectDir%impl\CSharp\TEST_cvAutoTrack_CSharp\TEST_cvAutoTrack_CSharp.csproj /t:restore
        - MSBuild %MyProjectDir%impl\CSharp\TEST_cvAutoTrack_CSharp\TEST_cvAutoTrack_CSharp.csproj /p:configuration="Compile"
        
    after_build:
        - echo %MyProjectDir%cvAutoTrack.sln 编译完成 等待测试
        - mkdir %MyProjectDir%x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.dll $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.lib $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\include\*.h $env:MyProjectDir\x64\build\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\cvAutoTrackCSharp.cs $env:MyProjectDir\x64\build\
    
        
    before_test:
        # 移动测试文件到test目录
        - mkdir %MyProjectDir%x64\test\
        - cd %MyProjectDir% 
        - ls -R
        - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Compile\*.dll $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\Cpp\TEST_cvAutoTrack_Cpp\x64\Compile\*.exe $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.exe $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.dll $env:MyProjectDir\x64\test\
        - ps: cp -r $env:MyProjectDir\impl\CSharp\TEST_cvAutoTrack_CSharp\bin\x64\Compile\net6.0\*.json $env:MyProjectDir\x64\test\
        
    test_script:
        - cd %MyProjectDir%\x64\test\
        - dir
        # 运行 C++ 测试
        - TEST_cvAutoTrack_Cpp.exe -test
        # 运行 C# 测试
        - TEST_cvAutoTrack_CSharp.exe -test
                
-
    version: '7.0.0.{build}'
    os: Visual Studio 2022
    configuration: Chore
    platform:
        - x64
    branches:
      only:
        - /chore-/

    environment:
        SecureAliConfig: HKh20duMUEcO6HEKkDzsUYS2qgSpQKrNmVOkKd7hC5JNHtPdLa+6giA5IwNxBeYG0e9cbaVlIl7r9UjswYF09nRljRGz9fHXN90/4HUyuxSwtH65HJmSSPIOM7QfXqAdxUjBXCZ2iwlnn3JYPD603JQgKUypTtCdlWUNRxtPFObDq2yPXlwvw02a4u4e7ze1n9oiEF9r1RmLHs4D3wrhVw==
        MyProjectDir: C:\projects\genshinimpact-autotrack-dll\
        OpenCvDir: C:\projects\opencv\
        OpenCvUrl: https://github.com/GengGode/OpencvStaticLib/releases/download/4.6.0/Opencv.zip
        ProjectName: cvAutoTrack
        ProJectExeName: cvAutoTrack
    skip_tags: true
  
    install:
        - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()

        #- mkdir %OpenCvDir%
        #- appveyor DownloadFile %OpenCvUrl%
        #- 7z x ./*.zip -y -o%OpenCvDir%
        #- rm -f ./*.zip
        #
        #- cd %MyProjectDir%\%ProjectName%\
        #- 7z x ./resource.rar -y -o%MyProjectDir%\%ProjectName%\
        
    build_script:
        - echo 获取版本号
        - echo %APPVEYOR_BUILD_VERSION%>version.ver
        - echo %APPVEYOR_BUILD_VERSION%>build_version.ver
        - ps: $version = Get-Content version.ver
        - ps: echo (Get-Content build_version.ver)
        - 7z a -tZip cvAutoTrack-%APPVEYOR_BUILD_VERSION%.zip cvAutoTrack.sln
        - ps: dir
        - ps: $version = Get-Content version.ver
        - ps: (Get-FileHash -Path cvAutoTrack-$version.zip -Algorithm MD5).Hash | out-file md5.hash
        - ps: echo (Get-Content md5.hash)
        - echo 测试上传
        - curl -L "https://github.com/aoaostar/alidrive-uploader/releases/download/v2.2.1/alidrive_uploader_v2.2.1_windows_amd64.zip" -o alidrive.zip 
        - tar -xf alidrive.zip --strip-components 1
        - dir
        - del example.config.yaml
        - ps: Out-File -FilePath config.yaml -InputObject "$SecureAliConfig"
        - dir
        - ps: echo (Get-Content build_version.ver)
        - ps: .\alidrive.exe .\cvAutoTrack-$version.zip /cvAutoTrack
        
        - $version = Get-Content version.ver
        - $buildversion = Get-Content build_version.ver
        - $md5 = Get-Content md5.hash
        - $commitLog = git log -1 --pretty=%B
        
        - $token="${{secrets.GENSHINTIANLIBATTLECLIENTUPDATE_ARTIFACT_TOKEN}}"
        - $url='http://update.api.weixitianli.com/GenshinTianLiBattleClient/Version?token='+$token
        - $body='{"version":"' + $version+'","description":"' + $buildVersion + '","downloadUrl":"http://download.weixitianli.com/d/TianLiUpdateService/GenshinTianLiBattleClient/GenshinTianLiBattleClient-' + $version + '.zip","hash":"' + $md5 + '","updateLog":"' + $commitLog + '"}'
        - echo $url
        - echo $body
        - Invoke-RestMethod -Method Post -Uri $url -Body $body -ContentType 'application/json'